<?php
$this->headScript()->appendFile($this->assetUrl('js/properties-array.js', 'ISTCIDOC'), 'text/javascript', array('id' => 'properties_array'));
$this->headScript()->appendFile($this->assetUrl('js/resource-form.js', 'ISTCIDOC'));

$escape = $this->plugin('escapeHtml');
$formLabel = $this->plugin('formLabel');
$formElement = $this->plugin('formElement');
?>
<?php $this->trigger("view.$action.form.before", ['form' => $form]); ?>

<?php echo $this->partial('istcidoc/common/resource-fields.phtml', [
    'form' => $form,
	'resource' => $item,
]); ?>

<div id="page-actions">
    <?php if ($item && $item->isPublic() || !isset($item)): ?>
    <?php echo $this->hyperlink('', '#', [
        'class' => 'o-icon-public button',
        'title' => $this->translate('Make private'),
    ]); ?>
    <input type="hidden" name="o:is_public" value="1">
    <?php else: ?>
    <?php echo $this->hyperlink('', '#', [
        'class' => 'o-icon-private button',
        'title' => $this->translate('Make public'),
    ]); ?>
    <input type="hidden" name="o:is_public" value="0">
    <?php endif; ?>
    <?php echo (isset($deleteButton)) ? $deleteButton : ''; ?>
    <button type="submit" name="add-item-submit"><?php echo $escape($submitLabel); ?></button>
</div>

<?php $this->trigger("view.$action.form.after", ['form' => $form]); ?>

<?php echo $formElement($form->get('csrf')); ?>

<?php echo $this->partial('istcidoc/common/resource-form-templates.phtml'); ?>
