<?php
$this->headLink()->prependStylesheet($this->assetUrl('css/advanced-search.css', 'ISTCIDOC'));
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'ISTCIDOC'));


$query = isset($query) ? $query : null;
$partials = [
    'istcidoc/common/advanced-search/properties',
];

$filterResults = $this->trigger(
    'view.advanced_search',
    [
        'query' => $query,
        'resourceType' => isset($resourceType) ? $resourceType : null,
        'partials' => $partials,
    ],
    true
);
$partials = $filterResults['partials'];
?>

<div class="advanced-search-content">
<?php
foreach ($partials as $partial) {
    echo $this->partial($partial, ['query' => $query]);
}
?>
</div>
