<?php
$escape = $this->plugin('escapeHtml');
$this->dataTypeCIDOC()->prepareForm();
?>

<div class="resource-values field template" role="group">
    <div class="field-meta">
        <div class="field-label"></div>
        <a href="#" class="collapse" aria-label="<?php echo $escape($this->translate('Collapse')); ?>"></a>
        <div class="collapsible">
            <div class="field-description"></div>
            <div class="field-term"></div>
        </div>
    </div>
    <div class="inputs">
        <div class="values">
            <p class="no-values"><?php echo $this->translate('Select the first value type.'); ?></p>
        </div>
        <div class="add-values default-selector">
            <a href="#" class="add-value button o-icon-literal" data-type="literal"><?php echo $this->translate('Text'); ?></a>
            <a href="#" class="add-value button o-icon-resource" data-type="resource_cidoc"><?php echo $this->translate('ISTCIDOC resource'); ?></a>
            <a href="#" class="add-value button o-icon-uri" data-type="uri"><?php echo $this->translate('URI'); ?></a>
            <a href="#" class="add-value button o-icon-location" data-type="location"><?php echo $this->translate('Location'); ?></a>
        </div>
    </div>
</div>

<?php echo $this->dataTypeCIDOC()->getTemplates(); ?>
