<?php
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>
<?php foreach ($values as $term => $propertyData): ?>
    <div class="property">
        <h4>
        <?php if ($propertyData['alternate_label']): ?>
        <?php echo $escape($propertyData['alternate_label']); ?>
        <?php else: ?>
        <?php echo $escape($this->translate($propertyData['property']->label())); ?>
        <?php endif; ?>
        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
        </h4>
        <div class="values">
        <?php foreach ($propertyData['values'] as $value): ?>
            <?php
            $class = ['value'];
            $class[] = 'resource';
            if ('literal' == $value->type()) {
                $class[] = 'resource';
            } elseif ('resource' == $value->type()) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $value->type()) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }
            ?>
            <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($propertyData['property']->term() == 'istcidoc:location') { ?>
                   <?php echo "<a style='color: blue' title=" . $value->lang() ." class='resource-link' href='../location/" . $value->asHtml() . "'><span class='resource-name'>" . $value->lang() . "</span></a>"; ?>
                <?php } else{ echo $value->asHtml(); } ?>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
