<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
?>

<?php echo $this->pageTitle($item->local(), 2); ?>
<h3><?php echo $translate('Item'); ?></h3>
<?php $this->trigger('view.show.before'); ?>
<div id="item-metadata" class="active section">
        <div class="meta-group">
            <h4><?php echo $translate('Location URI'); ?></h4>
            <div class="value"><?php echo $escape($item->uri()); ?></div>
        </div>
         <div class="meta-group">
            <h4><?php echo $translate('Location Title'); ?></h4>
            <div class="value"><?php echo $escape($translate($item->local())); ?></div>
        </div> 
        <div class="meta-group">
            <h4><?php echo $translate('Location Position'); ?></h4>
            <div class="value"><?php echo $escape($translate($item->position())); ?></div>
        </div>
</div>

<?php
$page = $this->params()->fromQuery('page', 1);
?>

<?php $this->trigger('view.show.after'); ?>
